_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 08597c78-b83d-4a14-b96b-8d388839ef09
name: 'Employee Portal'
mail: sourav.chandra@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /index
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
